version = 1

[envs.neovim]
channels = ["conda-forge"]
dependencies = { nvim = ">=0.10" }
exposed = { nvim = "nvim" }

[envs.cli]
channels = ["conda-forge"]
dependencies = { ripgrep = "*", fd-find = "*", fzf = "*", lazygit = "*", git = "*", gcc = "*", make = "*", unzip = "*", tree-sitter-cli = "*", tmux = "*" }
exposed = { rg = "rg", fd = "fd", fzf = "fzf", lazygit = "lazygit", git = "git", gcc = "gcc", make = "make", unzip = "unzip", tree-sitter = "tree-sitter", tmux = "tmux" }

[envs.fish]
channels = ["conda-forge"]
dependencies = { fish = "*" }
exposed = { fish = "fish" }

[envs.node]
channels = ["conda-forge"]
dependencies = { nodejs = ">=20" }
exposed = { node = "node", npm = "npm", npx = "npx" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "3.12.*", uv = "*" }
exposed = { python = "python", uv = "uv" }
